### ISSUE TITLE
Bot connected, but cannot use slash commands

### ISSUE THREAD

**Issue by t4m0thy** [winglessraven/AMP-Discord-Bot#106]
**Describe the bug**
Slash command cause an error in the application

**To Reproduce**
Steps to reproduce the behaviour:
configure discord bot in AMP and on Discord server
Bot is connected
run "/info" in text channel
discord will time out with "The application did not respond"

**Expected behaviour**
Some manner of info panel

**Screenshots**
![image](https://github.com/user-attachments/assets/9807290e-6e45-4e02-89b4-ca2a5295a5ca)
![image](https://github.com/user-attachments/assets/fadd5622-408c-4eaf-aa05-b625ab41450b)
![image](https://github.com/user-attachments/assets/8ffa49d7-881d-4344-aa0e-41d8ebc16d21)
![image](https://github.com/user-attachments/assets/a1b9f75b-705e-4bb0-af7c-cbb65496c476)
![image](https://github.com/user-attachments/assets/518d428c-86b5-4565-bb00-57893a1ecb12)

[AMPLOG2.log](https://github.com/user-attachments/files/16478993/AMPLOG2.log)

**AMP Instance Info (please complete the following information):**
 - OS: Windows 11
 - AMP Build 2.5.1.2 - 20240724.5

**Additional context**
It's entirely possible I've missed something (not a case of it having worked previously, new setup)

**Comment by winglessraven** [comment]
Can you add the logs from the AMP instance? That might help see what's going on.

**Comment by t4m0thy** [comment]
The attachment amplog2.log is a full log from the instance

**Comment by winglessraven** [comment]
Totally missed that xD

The log suggests there is a permission missing on the Discord side: `A SlashCommandExecuted handler has thrown an unhandled exception.:
Discord.Net.HttpException: The server responded with error 50013: Missing Permissions`

Looks like the bot does not have permission to send messages in the channel you are running the command in.

**Comment by t4m0thy** [comment]
And there's me trying to add more permissions to the bot! not even considering the obvious. Thank you very much for helping me even though it had nothing to do with your app.
Have a beer on me

**Comment by winglessraven** [comment]
Glad you got it working. Thanks very much, appreciate it!
