### ISSUE TITLE
"Online Players" and "Top 5 players by play time" in server info panel don't appear to be able to handle spaces in player name

### ISSUE THREAD

**Issue by t4m0thy** [winglessraven/AMP-Discord-Bot#107]
**Describe the bug**
info panel display sections only show the first word in a player name when the name contains one or more spaces

**To Reproduce**
1. Setup the discordbot and display the info panel in a channel (brilliant feature)
2. Have one or more players join with napes containing spaces

**Expected behaviour**
Names for joined players or top players by play time to contain full names including spaces

**Screenshots**
![image](https://github.com/user-attachments/assets/76360f55-89d1-4b16-a1ba-a1993aa7be34)

**AMP Instance Info (please complete the following information):**
 - OS: Windows 11
 - AMP Build 2.5.1.2 - 20240724.5

**Additional context**
As I'm fairly new to AMP I can't say if it's AMP or the discord bot.
If it makes any difference I'm seeing this on palworld but not tried other games

**Comment by winglessraven** [comment]
Can you check the console tab inside AMP when the player with a space in the name is connected? The connected players show on the right hand side.

If it shows correctly in AMP then it is indeed a bug and I will aim to fix it.

**Comment by t4m0thy** [comment]
Apologies, that's two for two not your code, AMP displays the username incorrectly
