### ISSUE TITLE
Feature Request: Public IP variable for Server Connection URLs

### ISSUE THREAD

**Issue by Kelarik** [winglessraven/AMP-Discord-Bot#114]
It would be great if a variable could be used in the Server Connection URL box, to pull the server's public WAN IP.

Some games, V Rising being the one I most recently encountered, do not allow the use of hostnames for connection. For those of us with dynamic IPs, it would be convenient if the Server Connection URL could be set to something like {PublicIP}:12345, and have it resolve as appropriate for the Discord Bot info panels.

**Comment by winglessraven** [comment]
Sounds like a good idea! Will try to take a look sometime this week.

**Comment by winglessraven** [comment]
Added in new release ... https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.22.1

Use `{PublicIP}` in the connection URL setting.
