### ISSUE TITLE
CryptographicException Plugin can not load

### ISSUE THREAD

**Issue by johnbli** [winglessraven/AMP-Discord-Bot#14]
02:07:25
Loaded ADSModule version 1.0.0.0 by CubeCoders Limited
Loaded FileManagerPlugin version 1.0.0.0 by CubeCoders Limited
Loaded EmailSenderPlugin version 1.0.0.0 by CubeCoders Limited
Loaded WebRequestPlugin version 1.0.0.0 by CubeCoders Limited
Loaded LocalFileBackupPlugin version 1.0.0.0 by CubeCoders Limited
Loaded CommonCorePlugin version 1.0.0.0 by CubeCoders Limited
CryptographicException
[0] (CryptographicException) : Das angeforderte Objekt wurde nicht gefunden.
at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr) at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName) at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags) at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
Unable to load plugin DiscordBotPlugin: Could not load file or assembly 'DiscordBotPlugin' or one of its dependencies. Failure during Cryptographic operation. (Exception from HRESULT: 0x80131430)
Could not load plugin DiscordBotPlugin
ADSModule requests dependency InstanceManagerPlugin...
02:07:26
Loaded InstanceManagerPlugin version 1.0.0.0 by CubeCoders Limited
ADSModule requests dependency SystemUserManagerPlugin...
Loaded SystemUserManagerPlugin version 1.0.0.0 by CubeCoders Limited
Loaded steamcmdplugin version 1.0.0.0 by CubeCoders Limited
Metrics server started OK on port 12820
Using keypair with fingerprint oai5JtFNC31m74AiilpceJ6EwSuA2rzmJ0Jz+X4ylFM=
SFTP Server started on 0.0.0.0:2223
02:07:27
Websockets are enabled.
Webserver started on http://0.0.0.0:8080
RouterTimer@10Hz with 2 jobs started
Checking for AMP updates...
AMP is up-to-date.

**Comment by winglessraven** [comment]
That looks like you're either trying to run it on ADS or your dev license isn't activated correctly?  The plugin only works on instances currently.  ADS cannot be activated with a developer license correctly (below those lines in the log you should see the licence status, e.g...
```
[10:45:13] [Core Info]            : Licence Present: AMP Patreon Supporter Edition (Licenced to XXXXX)
[10:45:13] [Core Info]            : Licence Present: AMP Developer Edition (Licenced to XXXXX)
```

**Comment by johnbli** [comment]
i have activate a AMP Developer Licence on my ADS Instance with windows cmd

**Comment by johnbli** [comment]
do i have to put the discord plugin into each game server instance and activate a developer license for each instance ?

**Comment by winglessraven** [comment]
Yep correct, the plugin only works with game server instances.  Activating dev licences for ADS is not currently an option.  When it becomes an option from CubeCoders I will write another bot that can monitor all instances.

**Comment by johnbli** [comment]
how many developer licenses are allowed to activate with AMP i currently have 6 game server instances

**Comment by winglessraven** [comment]
Currently the limit is 5, but from my understanding it's not enforced that much (as long as it's not abused) so more than 5 can be activated.

Also, hopefully in an AMP release a little later down the line we won't need to use developer licences to use the plugin any more.
