### ISSUE TITLE
Missing Dependency (Newtonsoft.Json.dll)

### ISSUE THREAD

**Issue by Muqluk** [winglessraven/AMP-Discord-Bot#27]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
Setting up on a windows 2022 server following all instructions to completion, the discord bot did not display in the Instance > Configuration menu.  There were no apparent errors in either console (primary AMP console nor the target game instance console)

After some investigation I identfied the following error(s)
```
[00:02:42] [Core Error]           :    at Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
   at Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
   at GSMyAdmin.SignatureVerification.Verify_Windows(String Filename)
[00:02:42] [ModuleLoader Error]   : Missing plugin/assembly: Newtonsoft.Json (D:\AMPDatastore\Instances\ModsTestingInstance\Plugins\DiscordBotPlugin\Newtonsoft.Json.dll)
...
...
[00:02:42] [ModuleLoader Error]   : Unable to load plugin DiscordBotPlugin: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
[00:02:42] [ModuleLoader Error]   : Could not load plugin DiscordBotPlugin
```

I was able to resolve the issue via manually downloading Newtonsoft.Json.dll 13.0.1 via nuget and placing the missing dependency within the DiscordBotPlugin folder, along side the DiscordBotPlugin.dll

The Menu item is now displaying as expected within the instance configuration menu.
(It is late and I've spent a few hours on this so time for bed.  If there are downstream issues configuring and connecting the bot itself I will edit and/or reply with findings and relevant information.)

**AMP Instance Info (please complete the following information):**

AMP Release "Triton"
v2.3.2.10, built 21/04/2022 15:09

Host OS and Module:  Windows Server 2022 ADS Instance
Target Instance:  

**Additional context**
Suggest one of the following:
1. update documentation to direct users to the above corrective action if they encounter the same issue.
1. Add the Newtonsoft.Json.dll dependency file to the linked 'latest version download' in the current documentation
1. Embed the dependency as a resource within the DiscordBotPlugin.dll allowing the continued 'single-file download' paradigm

**Comment by winglessraven** [comment]
That's what I get for not testing this release on Windows!

Release [1.10.1](https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.10.1) includes Newtonsoft.Json in the assembly.

**Comment by Muqluk** [comment]
Also encountering a serialization error in the log files. 

Unsure if it’s a misconfiguration on my part or not however. 

Error converting {null} to type Discord.Optional

Will get the full exception for you tomorrow - on a mobile device now and AMP is not kind to mobile displays

**Comment by winglessraven** [comment]
OK thanks for the info - will wait to see the full exception.

**Comment by Muqluk** [comment]
I think it’s safe to disregard. 

Started over fresh with a clean instance and a new bot and no troubles this time - so I monkeyed something up. 

Thank you for the rapid responses however!

**Comment by winglessraven** [comment]
Great news, glad it's working OK now.

Feel free to reach out with any feature requests or bug reports.
