### ISSUE TITLE
Don't show configuration Panel

### ISSUE THREAD

**Issue by oscarpedrero** [winglessraven/AMP-Discord-Bot#30]
[12:13:51] [ModuleLoader Info] ???: Loaded DiscordBotPlugin version 1.0.0.0 by CubeCoders Limited

Load perfect in instance and have DiscordBotPlugin.kvp in filesystem of Instance, but don't see config panel.

I restart all AMP Instance, Server Instance anddon't show panel in web admin.

 - OS: Ubuntu 22
 - AMP Build: AMP Release "Triton" v2.3.4, built 16/06/2022 16:08

**Comment by winglessraven** [comment]
Two questions:
1. What type of instance did you add it to?
2. Can you grab the latest AMP log file so I can check it (remove any personal info first)?

**Comment by oscarpedrero** [comment]
Docker Instance of Vrising.

ok in my last log i see:

 [12:49:00] [ModuleLoader Error]   : Unable to load plugin DiscordBotPlugin: A developer licence is required to load unsigned plugins.
[12:49:00] [ModuleLoader Error]   : Could not load plugin DiscordBotPlugin

How its osible if i reactivate instance and say [12:13:51] [ModuleLoader Info] ???: Loaded DiscordBotPlugin version 1.0.0.0 by CubeCoders Limited

**Comment by oscarpedrero** [comment]
[14:12:48] [Core Info] ???????????: Starting AMP version 2.3.4.0 (Triton), built 16/06/2022 16:08
[Info] [14:12:48] [Core Info] ???????????: Stream: Mainline (Release) - built by CUBECODERS/buildbot on CCL-DEV
[Info] [14:12:48] [Core Info] ???????????: Running in a QEMU KVM environment.
[Info] [14:12:48] [Core Info] ???????????: AMP Instance ID: 3ade846b-9018-4536-bec2-a8184d6efc47
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded GenericModule version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [Core Info] ???????????: Metrics publishing is enabled at udp://localhost:12820.
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded FileManagerPlugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded EmailSenderPlugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded WebRequestPlugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded LocalFileBackupPlugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded CommonCorePlugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded DiscordBotPlugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: GenericModule requests dependency steamcmdplugin...
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded steamcmdplugin version 1.0.0.0 by CubeCoders Limited
[Info] [14:12:49] [ModuleLoader Info] ???: GenericModule requests dependency RCONPlugin...
[Info] [14:12:49] [ModuleLoader Info] ???: Loaded RCONPlugin version 1.0.0.1 by CubeCoders Limited
[Info] [14:12:49] [Scheduler Warning] ???: Schedule trigger 45e983cb-e0fc-4de4-8b38-4349d0e5738e has a mismatched ID!
[Info] [14:12:49] [Scheduler Warning] ???: Schedule trigger 16f26b58-1230-4626-8f2a-4ccfa22358a9 has a mismatched ID!
[Info] [14:12:49] [Scheduler Warning] ???: Schedule trigger 27213f1d-78c9-4024-83ac-5ed45cb2d282 has a mismatched ID!
[Info] [14:12:49] [Scheduler Warning] ???: Schedule trigger a5b4ebcb-4af2-4ebf-afa8-cd84e965ba1f has a mismatched ID!
[Info] [14:12:49] [Core Warning] ????????: No such setting node: GenericModule.Meta.OriginalSource - maybe the relevant plugin/module isn't loaded?
[Info] [14:12:49] [Core Warning] ????????: No such setting node: GenericModule.App.TemplateMatchRegex - maybe the relevant plugin/module isn't loaded?
[Info] [14:12:49] [Core Info] ???????????: Performing activation, please wait...
[Info] [14:12:50] [Core Info] ???????????: Activated successfully.
[Info] [14:12:50] [Core Info] ???????????: Licence Present: AMP Developer Edition (Licenced to Oscar Pedrero Feliciano)
[Info] [14:12:50] [Core Info] ???????????: -configonly specified or activation performed. Saving settings and shutting down. This is perfectly normal.

**Comment by winglessraven** [comment]
You got it :)

Unfortunately an AMP limitation until there is a way to use plugins without the developer licenses.

**Comment by winglessraven** [comment]
As a side note, I think it's possible to use the plugin if you create the instance outside of a container, add the dev licence and plugin, and then edit the instance settings and put it in a container.

**Comment by oscarpedrero** [comment]
How do it? Interesting ....
