### ISSUE TITLE
Info Panel and Admin Panel

### ISSUE THREAD

**Issue by FabiusHaselnuss** [winglessraven/AMP-Discord-Bot#31]
**Describe the solution you'd like**
an admin and player info panel

**Additional context**
would it be possible to make the info panel just an info panel where you set what to see like in the current info panel and then an admin panel with the buttons to start stop kill update etc.

So the current info panel as admin panel and an extra panel as info where address status and modpack url is seen as well as how many players are on it.

**Comment by winglessraven** [comment]
I've looked into it and this would require adding a lot more settings on the settings page, which is already quite cluttered.
If in the future there is a way to group/sort settings better (e.g. in sections on the same page) I will look into adding another panel option.
In the mean time I recommend using the permissions to restrict access to use the buttons or disable them and use commands.

**Comment by winglessraven** [comment]
Added in Release 1.12
