### ISSUE TITLE
Enabling Player Join/Leave Messages to channel for Minecraft causes instance crash

### ISSUE THREAD

**Issue by Codename-11** [winglessraven/AMP-Discord-Bot#32]
**Describe the bug**
I've done a little bit of testing and it seems that all functions of the plugin work as described except the Player Join/Leave Messages. 
I originally tested this with my Minecraft Forge 41.1.0 modded server, in which after setting up all the available options, I experienced an immediate AMP instance crash after I attempted to login. I initially thought it may be a mod I had causing a conflict, so to test, I created a new clean instance running Minecraft Forge 41.1.0 with no mods installed, went back through the DiscordBotPlugin installation steps, and attempted to join the server with the bot deactivated. This worked without issue. I then systematically enabled all the other options of DiscordBotPlugin, and testing in-between. No issues arose until I reached the aforementioned Player Join/Leave Messages option. 

Once enabled, I experienced the above described issue. Only though when a channel name was given. I have ensured that my Discord server has said channel created and it's not private or modified in any way after creation. 

I'm not positive that I'm not doing something incorrect, I would love some assistance, thanks!

**To Reproduce**
Steps to reproduce the behaviour:
1. DiscordBotPlugin Configuration Tab
2. Enable Player Join/Leave Messages and specify channel name
3. Attempt to join Minecraft server
4. See instance crash/shutdown and see error in log posted under "Additional Context".

**Expected behaviour**

**Screenshots**
![image](https://user-images.githubusercontent.com/10284999/183114069-8ae8ded3-2989-47d7-90b9-181d89f52ad2.png)

**AMP Instance Info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS 
 - AMP Build v2.3.4.4, built 26/07/2022 20:08

**Additional context**

[15:30:25] [User Authenticator #2/INFO]: UUID of player Codename_11 is 853e1862-88ed-46e8-8018-486433420937
[15:30:26] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@7d6ecfb2
[15:30:26] [Server thread/INFO]: Codename_11[/172.16.24.10:50181]: logged in with entity id 331 at (-63.58888183866694, 82.0, -52.754336705596906)
[15:30:26] [Server thread/INFO]: Codename_11 joined the game
[15:31:52] [API:admin Activity]   : Changing setting DiscordBotPlugin.DiscordBotSettings.PostPlayerEventsChannel to minecraft
[15:32:00] [Server thread/INFO]: Codename_11 lost connection: Disconnected
[15:32:00] [Server thread/INFO]: Codename_11 left the game
[15:32:00] [ErrorReporter Error]  : Unhandled Exception: Please report this to the AMP developers.
[15:32:00] [ErrorReporter Error]  : [Error] --- Begin Exception Data ---
[Error] OS: Linux (x86_64/QEMU_KVM)
[Error] Module: MinecraftModule, Version: AMP 2.3.4.4
[Error] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
[Error] Instance ID: d9355548-028d-463c-8a8c-d37d8894fd06
[Error] InvalidOperationException
[Error] [0] (InvalidOperationException) : Sequence contains more than one matching element
[Error]   at Linq.Enumerable.SingleOrDefault[TSource] (Collections.Generic.IEnumerable`1[T] source, Func`2[T,TResult] predicate)
  at DiscordBotPlugin.PluginMain.UserLeaves (Object sender, ModuleShared.UserEventArgs args) 
[Error] --- End Exception Data ---
[Warning] Unsigned plugins are loaded, error report will not be submitted.
[Warning] Last error was raised less than 60 minutes ago, error report will not be submitted.

[15:32:00] [ErrorReporter Info]   : ####################################
[15:32:00] [ErrorReporter Info]   : #         Self Diagnostics         #
[15:32:00] [ErrorReporter Info]   : ####################################
[15:32:00] [ErrorReporter Info]   : AMP Diagnostics could not establish a solution for this exception.

**Comment by winglessraven** [comment]
Can you show me the contents of your `DiscordBotPlugin.kvp` file from your instance folder?  Feel free to remove/change any identifiable info.

**Comment by Codename-11** [comment]
Good morning, here's the requested file! I appreciate your help. 
(GitHub wouldn't let me upload a .kvp so I zipped it.)
[DiscordBotPlugin.zip](https://github.com/winglessraven/AMP-Discord-Bot/files/9275156/DiscordBotPlugin.zip)
.

**Comment by winglessraven** [comment]
Thanks, that all looks OK.

Is it possible you have more than one channel called 'minecraft' on your Discord? I have managed to replicate the error by duplicating a channel name.

**Comment by Codename-11** [comment]
This is very possible, I checked and it does seem we have a voice-channel named minecraft as well. This didn't even cross my mind. I'll change the chat channel and update the plugin to reflect and report back. Thank you!

**Comment by winglessraven** [comment]
Awesome, hope that fixes it :) I'll leave this issue open and build in a way to handle duplicates in the next release 👍

**Comment by Codename-11** [comment]
I'm happy to report that changing the voice channel we had with the same name allows everything to work normally. Thank you again!

**Comment by winglessraven** [comment]
Fixed in Release 1.12
