### ISSUE TITLE
No Discord Bot in Configuration

### ISSUE THREAD

**Issue by Nome200** [winglessraven/AMP-Discord-Bot#33]
Hi.
I think i did everything described in the readme but i am not sure if i did it right. 
I am currently running AMP on a Windows PC
My AMPConfig.conf of my Minecraft Instance looks like that:
```
AMP.LoadPlugins=["FileManagerPlugin","EmailSenderPlugin","WebRequestPlugin","LocalFileBackupPlugin","CommonCorePlugin","DiscordBotPlugin"]
```
And i also added a folder with the DLL in it.
I also changed the license key to a dev key i hope. It did say done

**Comment by winglessraven** [comment]
Hey.
Can you attach your latest AMP log from the Minecraft instance (feel free to redact any personal info in there first)?

**Comment by Nome200** [comment]
I am currently on an iPad and apperantly i can't download or open the log file on it. I can probably send it tomorrow. 
Also, you do mean the AMP_Logs right? Because i for some reason have no access to open this folder in the integrated AMP File Manager.

**Comment by winglessraven** [comment]
Yep; AMP_Logs. You should be able to get it via the file manager if you open it from ADS then go into the instance folder from there.

**Comment by Nome200** [comment]
I can now access the files and the plugin is also working. I don't know why it didn't work before but that's what computers do sometimes. Thanks for your help anyways.

**Comment by winglessraven** [comment]
Great, glad it's working :)
