### ISSUE TITLE
Additional Info Panel

### ISSUE THREAD

**Issue by nooneawake** [winglessraven/AMP-Discord-Bot#34]
I would like to see an additional panel option that does not have the restart/kill buttons etc but allows discord users to see online players/server information/play time leader board.
![Screenshot 2022-09-08 084126](https://user-images.githubusercontent.com/37560936/189124308-49116eb6-9ce0-486d-8d8a-22f3c8948ca7.jpg)
only having the red circled section but not the blue section.

This would allow you to have a panel that allows for server controls and then an additional panel for the users where they can just see some information but not control the server.

**Comment by winglessraven** [comment]
Added in Release 1.12
