### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by Nome200** [winglessraven/AMP-Discord-Bot#38]
Can i use this plugin with multiple server instances? It doesnt seem to work. I think i reactivated the ADS instance with the dev key, but cant get the plugin work with a second game Server.

**Comment by winglessraven** [comment]
You can, but the plugin needs to run on each instance (and create a bot for each too). I have around 8 running at the moment.

The plugin will not run on ADS - there are complications when activating ADS with a dev licence (doesn't apply correctly).

**Comment by Nome200** [comment]
The plugin works perfectly with the minecraft server instance but not with the CSGO Instance.  I copied the files over from the MC server and put it in the CSGO instance.

**Comment by winglessraven** [comment]
It's worked with every instance type I've tried.  Can you see the settings for it in the menu for the CSGO instance?

**Comment by Nome200** [comment]
Nope

**Comment by Nome200** [comment]
`AMP.LoadPlugins=["FileManagerPlugin","EmailSenderPlugin","WebRequestPlugin","LocalFileBackupPlugin","CommonCorePlugin","DiscordBotPlugin"]
`

Thats the line in config and the directory exists with the dll in it

**Comment by winglessraven** [comment]
And you added the dev licence to the CSGO instance?

**Comment by Nome200** [comment]
to the ADS instance. 
I think. Can i check this?

**Comment by winglessraven** [comment]
You need to add it to each instance the plugin needs to run in, so for this one run `ampinstmgr reactivate csgoinstancename devkey`

**Comment by winglessraven** [comment]
If you run the command on ADS it'll say it's activating with the dev key but it doesn't

**Comment by Nome200** [comment]
Do I need multiple dev keys? If yes, how can i get more than one without buying more licenses with different accounts?

**Comment by winglessraven** [comment]
Nope, same key can be applied to multiple instances

**Comment by Nome200** [comment]
> If you run the command on ADS it'll say it's activating with the dev key but it doesn't

I ran this and it works now. Very nice. Thank you very much

One more thing: Is it neccessary to send a private message with the link to the Server management or can the "Manage" button contain the link itself. One extra step less

**Comment by Nome200** [comment]
I quoted the wrong one XD
I meant the one above

**Comment by winglessraven** [comment]
Great, glad it's working now

> One more thing: Is it neccessary to send a private message with the link to the Server management or can the "Manage" button contain the link itself. One extra step less

Originally it was just a link on the button but it was changed for security reasons (stop other non-management users spam clicking it etc)

**Comment by Nome200** [comment]
Ok that makes sense
