### ISSUE TITLE
channel.id instead of channel.name

### ISSUE THREAD

**Issue by AcesGamingUK** [winglessraven/AMP-Discord-Bot#39]
**Describe the solution you'd like**
Instead of putting in channel names, would it not be easier to use the channel ID?

**Additional context**
using channel names can be difficult as some guilds have channels with the same name nested under different categories,
so using names will only point to the first one it found, and not always the one you want

**Comment by winglessraven** [comment]
Valid point - I think at the time I couldn't find an easy way for users to get the Channel ID from Discord.

Is there a simple way to grab it (other than copying the channel link and using the last part)?

**Comment by AcesGamingUK** [comment]
there are a few ways, 
the easiest is by using the backslash
![Steam 29_October 00-42-09](https://user-images.githubusercontent.com/16180389/198751064-c6bf6157-8550-4128-be25-57c960a79c99.gif)

**Comment by winglessraven** [comment]
Implemented in release 1.12.2
