### ISSUE TITLE
Ability to change Command's access per role

### ISSUE THREAD

**Issue by zvarnes** [winglessraven/AMP-Discord-Bot#43]
**Describe the solution you'd like**
Change the '/[BOT NAME] command' to just '/command' so that the commands can be restricted per Discord role.

**Additional context**
This change would allow specified users to run certain commands and restrict others from being capable. For example an 'Admin' group would be able to run '/restart-server' but group 'everyone' would not be able to.

**Comment by winglessraven** [comment]
Hey,

I've had a look into it and this would require quite a big re-write (redo how the commands are registered, then in turn redo how they are received).

Have you tried using the permissions under the bot settings?

![image](https://user-images.githubusercontent.com/4540397/205312449-0bb86678-1a73-4c8e-ab22-11fcf1437fdd.png)

This will restrict usage to a specified role.

**Comment by zvarnes** [comment]
Yeah I saw that. It can also be done in the Discord settings I think. The issue with that is it restricts all commands. I'd like some users to be able to run 'full-playtime-list' or 'info', but not be able to start/stop/restart the server you know? If you were to make the change it would allow per-command access like this.

![image](https://user-images.githubusercontent.com/39716849/205363291-b74b97ef-622a-45b1-9ca0-d27ac0d4265c.png)

**Comment by winglessraven** [comment]
Got it, ok will try and take a look and see what I can do.

**Comment by winglessraven** [comment]
@zvarnes Added in the latest release. Please give it a try - I've tested as much as I can but I've got a limited setup at the moment so please report any issues and I'll fix.
