### ISSUE TITLE
Discord Bot Configuration label disappeared after AMP v2.4.1.2 update

### ISSUE THREAD

**Issue by LiveWithMadness** [winglessraven/AMP-Discord-Bot#45]
Hi, I've been a huge fan of this Cubecoders AMP Plugin as it gives so much QoL to the game servers' environments. Sadly (and it's not the first time), after an AMP update the Plugin very much "disappears" from the GUI. The folders and files are there, but AMP seems to not be able to initialize it. It happened before but the server was hosted on a Windows 10 Home machine and I thought it was just too many errors building up. This time, though, the server is hosted on an Ubuntu VM and so far worked flawlessly. I'll copy the error I managed to retrieve from the machine CLI as it can (maybe) provide more information and be more specific than I was.

Thank you in advance! And Merry Christmas (if you celebrate) and Happy Holidays!

> 

Can't find custom attr constructor image: /mnt/amp-storage/Datastore/Create01/Plugins/DiscordBotPlugin/DiscordBotPlugin.dll mtoken: 0x0a0090d7 due to: Method not found: void ModuleShared.StoreEncryptedAttribute..ctor()
[10:57:52] [ModuleLoader Error]   : Container failed to resolve plugin DiscordBotPlugin
[10:57:52] [ModuleLoader Error]   : Resolution of the dependency failed, type = 'DiscordBotPlugin.PluginMain', name = '(none)'.
Exception occurred while: Calling constructor DiscordBotPlugin.PluginMain(ModuleShared.ILogger log, ModuleShared.IConfigSerializer config, ModuleShared.IPlatformInfo platform, ModuleShared.IRunningTasksManager taskManager, ModuleShared.IApplicationWrapper Application, ModuleShared.IAMPInstanceInfo AMPInstanceInfo).
Exception is: MissingMethodException - Method not found: void ModuleShared.StoreEncryptedAttribute..ctor()
-----------------------------------------------
At the time of the exception, the container was:
  Resolving DiscordBotPlugin.PluginMain,(none)
  Calling constructor DiscordBotPlugin.PluginMain(ModuleShared.ILogger log, ModuleShared.IConfigSerializer config, ModuleShared.IPlatformInfo platform, ModuleShared.IRunningTasksManager taskManager, ModuleShared.IApplicationWrapper Application, ModuleShared.IAMPInstanceInfo AMPInstanceInfo)

[10:57:52] [ModuleLoader Fatal]   : 'DiscordBotPlugin' does not implement abstract class 'ModuleShared.AMPPlugin'
[10:57:52] [ModuleLoader Error]   : Could not load plugin DiscordBotPlugin

**Comment by winglessraven** [comment]
Hey,
I've not updated my instances yet but probably just need to recompile the plugin for the latest AMP release. For some releases it breaks and needs a rebuild against the new version. 
I'm heading out for the day shortly but will try to sort before I go. If not will fix it tonight.
Merry Christmas!

**Comment by LiveWithMadness** [comment]
Hi! Didn't expect such a fast response! Just enjoy your day, it's not a rush and definitely the services can be kept running without the Bot feature for a while! Again, thank you very much and don't stress it!

**Comment by winglessraven** [comment]
All done :) 
https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.13.0

Btw, the issues you had in the past could be due to the licence bug in AMP that would lose them on updates. I had the same problem on Windows but not on Linux.

Let me know if the recompiled version doesn't work for you (only tested quickly that it initialises correctly on the new AMP version) and I'll look further into it.

Have a good one :)

**Comment by LiveWithMadness** [comment]
Legend! Thank you so much!

PS. Didn't know you were also on the Discord Server (to be expected tbh,
clever me). Keep up the good work!
