### ISSUE TITLE
Feature Request: Adding player chats for minecraft and possibly other games

### ISSUE THREAD

**Issue by karutoil** [winglessraven/AMP-Discord-Bot#48]
I would love the feature that if a player chats in the game it will get synced to the discord and if someone chats in the discord it will get synced to the game

**Comment by winglessraven** [comment]
Sounds good, will take a look at what can be done over the weekend

**Comment by winglessraven** [comment]
Changes made in new release ... https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.14 

Important - you need to enable 'Message Content Intent' on your bot if you intend to send messages from Discord back to your server.
