### ISSUE TITLE
Ability to show Playfab Join Code in server info panel

### ISSUE THREAD

**Issue by dirkalakader** [winglessraven/AMP-Discord-Bot#59]
**Describe the solution you'd like**
I'd like to be able to have the bot grab the latest join code, maybe from the console output of an instance, and display/update that join code within the server info message. It would also be awesome if we could pull the IP:Port info from that same console output to display, although this doesn't change as often as the join code, so typing it into the bot is fine.

**Additional context**
I'm using the bot on a Valheim instance with crossplay enabled. The join code is output within the console of the instance with text:
```
Session "[servername]" registered with join code ######
Retry join-code check 99
Session "[servername]" with join code ###### and IP ###.###.###.###:#### is active with # player(s)
```

**Comment by winglessraven** [comment]
Could be tricky to do but I'll try and take a look at this over the weekend if I get time (Starfield may get in the way).

**Comment by winglessraven** [comment]
Option now added. Give it a go and let me know if working OK.
