### ISSUE TITLE
Erroneous Syntax chat for the pocket edition of Minecraft

### ISSUE THREAD

**Issue by Dhy19971** [winglessraven/AMP-Discord-Bot#61]
The console syntax used to capture and send messages in the game chat is incorrect on Minecraft Pocket Edition.

For example ''/say'' in Minecraft Java becomes ''say'' in Minecraft Pocket Edition.

I don't know if this observation is useful.

**Comment by winglessraven** [comment]
It seems like Bedrock doesn't like the `[` character when sending chat from Discord to the server. I get this error:
`[10:17:26] [2023-09-13 11:17:26:536 ERROR]: Syntax error: Unexpected "[": at "/say >>[<<test]"`

Is this what you mean? If so I can implement a quick fix by changing the character.

**Comment by Dhy19971** [comment]
Where can I change this? Many thanks for the reply.

**Comment by Dhy19971** [comment]
The problem is that. Thank you very much.

**Comment by winglessraven** [comment]
Get the new version here https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.16.1. Should fix the issue
