### ISSUE TITLE
"AMP was not updated correctly."

### ISSUE THREAD

**Issue by Waluijay** [winglessraven/AMP-Discord-Bot#63]
When attempting to launch an Instance with the bot installed, they will fail to launch and hang until stopped with no GUI error, error in logs state `AMP was not updated correctly.` All DiscordBot .dll versions result in the same error.

### To Reproduce
Follow steps until **Configure Your Discord Bot** in the [configuration section](https://github.com/winglessraven/AMP-Discord-Bot#configuration-steps)

### Expected behaviour
Instance restarts and is manageable, Discord Bot options become visible in the left-hand Instance Configuration menu.

### AMP Instance Info:
 - OS: Windows 10 Pro, clean installation specifically for testing error.
 - AMP Build 2.4.6.6 - 20231005.1, also clean install specifically for testing error.

**Additional context**
Attached are logs from AMP. "SUCCESS" runs AMP Instance with only DiscordBot .dll and .conf line removed. "FAIL" runs AMP Instance with only DiscordBot .dll and .conf line installed. All files moved/edited using AMP File Manager.

[AMPLOG 2023-10-06 05-43-03_FAIL.log](https://github.com/winglessraven/AMP-Discord-Bot/files/12827489/AMPLOG.2023-10-06.05-43-03_FAIL.log)
[AMPLOG 2023-10-06 05-44-03_SUCCESS.log](https://github.com/winglessraven/AMP-Discord-Bot/files/12827490/AMPLOG.2023-10-06.05-44-03_SUCCESS.log)

Unsure if this is an issue with the DiscordBot itself, or if the recent AMP update broke something the bot relies on, but figured I'd report to be safe.

**Comment by winglessraven** [comment]
Not seen that error before - I will update my systems after work today and do some checking.

What happens if you remove the 'DiscordBotPlugin' from the AMPConf and run the instance again? Does the error go away?

**Comment by winglessraven** [comment]
Sorry, just re-read your report. OK so probably something bot related. Will take a look later today.

**Comment by winglessraven** [comment]
Needed to recompile against the latest version of AMP.

This release should fix it... https://github.com/winglessraven/AMP-Discord-Bot/releases/tag/1.16.2
