### ISSUE TITLE
Application did not respond - Null Reference on GetServerInfo

### ISSUE THREAD

**Issue by alecfetterman** [winglessraven/AMP-Discord-Bot#66]
**Describe the bug**
- Unable to execute info command, play time does not log and no commands seem to work. I receive "The application did not respond" in Discord and the below runtime error.

**To Reproduce**
Steps to reproduce the behaviour:
- Executing the commands from discord channel.

**Expected behaviour**
Information to populate

**AMP Instance Info (please complete the following information):**
 - OS: Windows Server 2022
 - AMP Build: 2.4.6.6

**Additional context**
 I initially forgot to check application.commands, re-added the bot with the proper permissions and even tried adding as administrator. Not sure if I'm doing something completely wrong 😄 

Gateway A SlashCommandExecuted handler has thrown an unhandled exception.: System.NullReferenceException: Object reference not set to an instance of an object. at DiscordBotPlugin.PluginMain.<GetServerInfo>d__24.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at DiscordBotPlugin.PluginMain.<SlashCommandHandler>d__44.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Discord.EventExtensions.<InvokeAsync>d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() at Discord.WebSocket.DiscordSocketClient.<TimeoutWrap>d__172.MoveNext()

**Comment by winglessraven** [comment]
Can you add your instance logs and DiscordBotPlugin.kvp from the instance root folder pls? Feel free to remove any personal info and replace it with 'placeholder' or similar.

**Comment by alecfetterman** [comment]
Hey, thanks for the swift response!

Requested files attached. I included logs from earlier in the day too where we were running into the below error but those have since stopped. More than likely from wrong permissions but just wanted to include them since I noticed that was happening!

System.Exception: WebSocket connection was closed ---> Discord.Net.WebSocketClosedException: The server sent close 4003: "Not authenticated."


[DiscordBotPlugin.txt](https://github.com/winglessraven/AMP-Discord-Bot/files/13361207/DiscordBotPlugin.txt)
[AMPLOG 2023-11-15 01-27-16.log](https://github.com/winglessraven/AMP-Discord-Bot/files/13361208/AMPLOG.2023-11-15.01-27-16.log)
[AMPLOG 2023-11-15 04-42-18.log](https://github.com/winglessraven/AMP-Discord-Bot/files/13361209/AMPLOG.2023-11-15.04-42-18.log)

**Comment by winglessraven** [comment]
Great, thanks. I will take a look and see if I can replicate. It looks like the info panel was logged correctly, did it show in Discord? Also, the error you got was just from running the info command?

**Comment by winglessraven** [comment]
What type of instance are you running this on? If it's the main ADS then it will not work - the bot is for an instance, not ADS

**Comment by alecfetterman** [comment]
I was running it on the main ADS instance. It works great now when I configure it properly haha. I did not realize I had to make a bot per game server! That's okay we are only hosting 3 games on AMP at the moment. 30 other games using another platform 😅 

Thank you so much sir!

**Comment by winglessraven** [comment]
Awesome, glad you got it working.

Feel free to submit any feature requests if you find something missing that you need
