### ISSUE TITLE
Bot can't interact with AMP

### ISSUE THREAD

**Issue by SenpauKun** [winglessraven/AMP-Discord-Bot#75]
**Describe the bug**
While using the bot, AMP throws an error message as the bot sends requests to AMP. This is the error message. AMP is hosted in a local vm. I've attempted on both linux and windows with the same outcome.

`Gateway A SlashCommandExecuted handler has thrown an unhandled exception.: System.NullReferenceException: Object reference not set to an instance of an object at DiscordBotPlugin.PluginMain.GetServerInfo (System.Boolean updateExisting, Discord.WebSocket.SocketSlashCommand msg, System.Boolean Buttonless) [0x00075] in <cfd83e9e94c842678448dbfcc025904d>:0 at DiscordBotPlugin.PluginMain.SlashCommandHandler (Discord.WebSocket.SocketSlashCommand command) [0x0177d] in <cfd83e9e94c842678448dbfcc025904d>:0 at Discord.EventExtensions.InvokeAsync[T] (Discord.AsyncEvent`1[T] eventHandler, T arg) [0x000a0] in <cfd83e9e94c842678448dbfcc025904d>:0 at Discord.WebSocket.DiscordSocketClient.TimeoutWrap (System.String name, System.Func`1[TResult] action) [0x001d6] in <cfd83e9e94c842678448dbfcc025904d>:0`

It is not possible to create an info panel or use any other commands. The info command will make the bot display "The application did not respond", and the other commands will display the error message as seen above.

**To Reproduce**
Go through the usual installation process.

**Expected behaviour**
Clear communication between server and bot, so friends and I are able to remotely control whenever a game server should be running.

**AMP Instance Info (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - AMP Build v2.4.7

**Comment by winglessraven** [comment]
Hey, can you attach one of the AMP log files that contains the errors? Also, if poss the DiscordBotPlugin.kvp from the root instance folder.

With this I can try to replicate the issue.

**Comment by SenpauKun** [comment]
Hi again. Here's both the latest log file and the DiscordBotPlugin.kvp.
[ampLogAndDiscordBotPluginkvp.zip](https://github.com/winglessraven/AMP-Discord-Bot/files/13921048/ampLogAndDiscordBotPluginkvp.zip)

Thank you for the help, it is much appreciated.
