### ISSUE TITLE
Remove bot commands on removal

### ISSUE THREAD

**Issue by aminoginji** [winglessraven/AMP-Discord-Bot#81]
**Describe the bug**
removing bot from discord server does not delete commands

**To Reproduce**
Steps to reproduce the behaviour:
add bot to server
remove bot from server
**Expected behaviour**
all commands used by bot would be deleted from discord server

is there a set of manual api requests available so i can delete the bots commands or will i have to try and make them myself?

**Comment by aminoginji** [comment]
this is bugging me now i got postman setup to delete the commands but its telling me there are non yet i can see them and copy the id from discord

**Comment by winglessraven** [comment]
This would be a Discord issue anyway. If you remove the bot from a server then it cannot remove commands from a server it doesn't have access to.

**Comment by aminoginji** [comment]
you can add a /leave command that wipes its commandid and boots it from server. i just added and booted several bots and their commands leave with removal
