### ISSUE TITLE
DiscordBot - Permission Problem

### ISSUE THREAD

**Issue by eleminaiter** [winglessraven/AMP-Discord-Bot#88]
Hi, 

i installed the DiscordBot on my AMP Application. I got following Problem while i typing "/atlanticoreenshrouded info" command in Discord channel: "You do not have permission to use this command!". 

On my Discord-Server i got full permissions. I didnt found any settings to give my Account the Permission or something else about the AMP Application settings.

**Comment by winglessraven** [comment]
Have you got this option selected in your bot settings in the AMP panel?

![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/7b1d3fc9-521d-411b-949b-7774ba9d440d)

If so, you need to be a member of the role you set in the "Discord Role Name" option, e.g....

![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/bdfa80dc-6314-4aa6-8e3d-1f618ac6bf42)

![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/e51035b0-f823-4a94-b9fd-77567b17cca3)

**Comment by eleminaiter** [comment]
The option isnt turned on.

**Comment by winglessraven** [comment]
Can you show me a screenshot of the error?

**Comment by eleminaiter** [comment]
<img width="1500" alt="permission" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/1c82242f-fb92-4ecc-8f34-28ee1f294256">

**Comment by winglessraven** [comment]
Thanks, that shows the error is coming from the bot (and not Discord). Can you now share your `DiscordBotPlugin.kvp` file from the root of your instance?

**Comment by eleminaiter** [comment]
<img width="1290" alt="DiscordBotPlugin" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/dd468e22-a248-4f91-bae2-4a8b1141459c">

**Comment by winglessraven** [comment]
That all looks fine as well. This is strange.

The only place in the bot that returns that exact wording is when checking for permissions. RestrictFunctions is off, so the only place the code could be failing to allow you permission is line 1 below, this suggests that the bot is not seeing you as a "SocketGuildUser".

```C#
if (command.User is SocketGuildUser user)
{
    // The user has the permission if either RestrictFunctions is turned off, or if they are part of the appropriate role.
    hasServerPermission = !_settings.MainSettings.RestrictFunctions || user.Roles.Any(r => r.Name == _settings.MainSettings.DiscordRole);
}

if (!hasServerPermission)
{
    await command.RespondAsync("You do not have permission to use this command!", ephemeral: true);
    return;
}
```

This isn't something I've seen before so will need to try and replicate after work today. In the mean time can you double check you have the bot intents enabled as per the setup instructions?

**Comment by eleminaiter** [comment]
Should be on.

<img width="1881" alt="Intent" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/3f02c1ec-1666-4796-a95f-62d9bca2ab77">

**Comment by winglessraven** [comment]
Yeah, that all looks good.

If possible, can you also enable Discord debug mode, turn the bot off and on again, retry to create the info panel, then reply here with the AMP logs?

![image](https://github.com/winglessraven/AMP-Discord-Bot/assets/4540397/aa98c51c-91f3-443e-9542-d59be896c8c3)

**Comment by eleminaiter** [comment]
Is that enough? :)

<img width="1901" alt="log" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/c0cfb8b9-1ac6-4a87-9bee-e970770743c7">

**Comment by winglessraven** [comment]
This might be a strange question - but where are you running the `/atlanticoreenshrouded info` command? 
Only way I can replicate the same as you is if I try it in a DM to the bot, not in a channel on my Discord server.

**Comment by winglessraven** [comment]
Can you use this version? I've added some extra debugging to try and see what's going on.

Replace the existing dll with this one inside the zip file, restart your instance to reload the plugin, then run the command again and send me the AMP log.

[DiscordBotPlugin.zip](https://github.com/winglessraven/AMP-Discord-Bot/files/14793901/DiscordBotPlugin.zip)

**Comment by eleminaiter** [comment]
I replaced the .dll.

The Log:

<img width="1228" alt="Log" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/f147845b-0d93-4882-b6e2-b38b01276c95">

In Discord i get another message:

<img width="1495" alt="Discord" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/aa764e80-dfe3-4e30-88de-27163bf4af5d">

"The application is not responding"

**Comment by winglessraven** [comment]
So it looks like the bot cannot access either your username, server ID, channel ID or channel name. Attached should log which one, instead of giving the nullreference error. Can you try this one and reply with the log?
[DiscordBotPlugin.zip](https://github.com/winglessraven/AMP-Discord-Bot/files/14800486/DiscordBotPlugin.zip)

**Comment by eleminaiter** [comment]
<img width="1904" alt="Log" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/0aa8e815-2445-45a3-b5ed-4eac1237d9a4">

Now I got this message:

<img width="1496" alt="Discord" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/ca2c4d1f-91a2-468c-b018-b204752196a6">

**Comment by winglessraven** [comment]
Ignore the bot reply - I just put a different message in temporarily.

The log shows that the bot cannot get the channel you're trying to add the panel in. Does the bot have the correct permissions?

Can you try in another channel?

**Comment by eleminaiter** [comment]
I tried in different channels. Always the same problem.

How can i give the bot the permissions? There are no options for giving the bot a role.

<img width="1026" alt="bot" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/38b61639-6f6c-46fd-ae4a-a2d4b19fee5b">
<img width="801" alt="discord" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/a7dbb47d-1644-4db8-87df-65108bb35d11">

**Comment by winglessraven** [comment]
Try re-adding the bot to your server from https://discord.com/developers/applications/. 

Something seems wrong with how it's set up.

The URL you generate to join should end with `&permissions=92160&scope=applications.commands+bot`

**Comment by eleminaiter** [comment]
Thats my generated URL.

<img width="1896" alt="bot" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/14da9d73-7584-4cb7-aef1-2f92f0416df9">

**Comment by winglessraven** [comment]
That is missing `&permissions=92160`, so full url would be
`https://discord.com/oauth2/authorizeclient_id=[YOUR APPLICATION ID]&permissions=92160&scope=bot+applications.commands` (replacing with your application ID)

**Comment by eleminaiter** [comment]
Should be the right URL but...

<img width="1190" alt="bot" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/813aa946-9cd5-4d86-b920-9455026cfe06">

**Comment by winglessraven** [comment]
I've not seen that before 🤔

Double check the setup of your application. Did you change any settings when you created the application?

Maybe check the Installation page on Discord developers - it should be the default "Guild Install"

**Comment by eleminaiter** [comment]
I found the Problem :) WUHU :D 

Installed the bot over the Installation button:

<img width="1810" alt="bot" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/9a98adb6-03f5-47b4-9e20-73b023dd6212">

Now it Works:

<img width="1706" alt="Discord" src="https://github.com/winglessraven/AMP-Discord-Bot/assets/34658148/93f0cadd-d7c0-45f3-9430-7cb39d563898">

**Comment by winglessraven** [comment]
Ahhh, yeah that'll do it.

Awesome, glad you got it working :)

**Comment by eleminaiter** [comment]
Just a little mistake :) 

Thanks for your help :D

**Comment by winglessraven** [comment]
No probs :)
