### ISSUE TITLE
Container failed to resolve plugin DiscordBotPlugin

### ISSUE THREAD

**Issue by Schlaager** [winglessraven/AMP-Discord-Bot#9]
Hey,

I just tried to install the bot plugin in AMP. After following all the steps you provided, the console put out this: 
![DiscordBotPlugin](https://user-images.githubusercontent.com/72343058/149030256-c0ad9ce1-e96b-4e99-93f6-9287d20eaf8c.PNG)
For any help I would be very thankful.

Best regards
Schlaager

**Comment by winglessraven** [comment]
Can you confirm the OS your instance is running in?  Also are you running in a Docker container?

**Comment by Schlaager** [comment]
I am running Ubuntu 20.04 and it's not within a Docker Container.

**Comment by winglessraven** [comment]
OK thanks, can you also confirm which build of AMP the instance is running?

**Comment by Schlaager** [comment]
AMP is running on Version 2.3.0.8 (MainLine Build)

**Comment by winglessraven** [comment]
I've tried replicating on 20.04 and I'm not getting any errors.  What type of instance are you adding this to?  It's not ADS is it?

**Comment by winglessraven** [comment]
Other thing to check is that you grabbed the correct dll - can you let me know the size of the file you have?

**Comment by winglessraven** [comment]
Awesome news, glad it's working now :)  Feel free to reach out with any feature requests
