### ISSUE TITLE
The Bot Does Not Turn On

### ISSUE THREAD

**Issue by nmill22** [winglessraven/AMP-Discord-Bot#96]
**Describe the bug**
I followed every step in the setup process, skipping the install script, and I was able to set all the bot configurations. But when I restart the instance, nothing happens. The bot does not turn on and come online in my Discord server. I currently developed Discord bots, so I know I set everything up correctly. I'm just not entirely sure why the bot would not be starting with the instance, or if i missed something. Any help on this issue would be appreciated.

**To Reproduce**
Steps to reproduce the behaviour:
Follow every step of the setup process, not using install script.

**Expected behaviour**
The bot to run.

**AMP Instance Info (please complete the following information):**
 - OS: Linux
 - AMP Build 2.5.0.8

**Comment by medic4085** [comment]
Did you run the command /"botname" info within the discord channel you wanted it to show in? Otherwise, only configured items with a channel ID will automatically report to discord.

Either-way, this is working fine for me.  I would be curious to see your logs as well.
